# Generated by Django 3.2.23 on 2023-12-13 20:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=8)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('especialidad', models.CharField(choices=[('clinica', 'Psicología Clínica'), ('educativa', 'Psicología Educativa'), ('deporte', 'Psicología del Deporte'), ('organizacional', 'Psicología Organizacional'), ('forense', 'Psicología Forense'), ('salud_mental', 'Salud Mental'), ('terapia_familiar', 'Terapia Familiar'), ('neuropsicologia', 'Neuropsicología'), ('psicologia_infantil', 'Psicología Infantil'), ('psicoterapia', 'Psicoterapia'), ('psicologia_social', 'Psicología Social'), ('gerontologia', 'Gerontología'), ('psicologia_rehabilitacion', 'Psicología de la Rehabilitación'), ('psicologia_educacional', 'Psicología Educacional'), ('psicologia_legal', 'Psicología Legal'), ('orientacion_vocacional', 'Orientación Vocacional'), ('terapia_sexual', 'Terapia Sexual'), ('terapia_pareja', 'Terapia de Pareja'), ('psicologia_transpersonal', 'Psicología Transpersonal'), ('otra_especialidad', 'Otra Especialidad')], max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('institucion_otorgamiento', models.CharField(max_length=200, verbose_name='Institución de otorgamiento')),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True, null=True)),
                ('curriculum', models.FileField(blank=True, null=True, upload_to='curriculum_psicologo/')),
                ('foto_perfil', models.ImageField(blank=True, upload_to='psicologos_foto_perfil/')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados_psicologos/')),
                ('identificacion_oficial', models.FileField(blank=True, null=True, upload_to='identificacion_psicologos/')),
                ('enlace_pagina_web', models.URLField(blank=True, null=True)),
                ('enlace_facebook', models.URLField(blank=True, null=True)),
                ('enlace_instagram', models.URLField(blank=True, null=True)),
                ('enlace_linkedin', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('diario', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=254, null=True, verbose_name='Descripción')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('horario_atencion', models.TimeField(blank=True, null=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psicologo.psicologo', verbose_name='Consultorio')),
            ],
        ),
    ]
