# Generated by Django 3.2.23 on 2023-12-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0004_alter_consultorio_psicologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='costo_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Consulta'),
        ),
    ]
