# Generated by Django 3.2.23 on 2024-01-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0008_auto_20240109_1826'),
        ('psicologo', '0008_psicologo_contactos'),
    ]

    operations = [
    ]
