# Generated by Django 3.2.23 on 2024-01-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0009_merge_20240110_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='solicitudes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
