# Generated by Django 3.2.23 on 2023-12-13 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutriologo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('ocupacion', models.CharField(max_length=100, verbose_name='Ocupación')),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='pacientes_foto_perfil/')),
                ('descripcion', models.CharField(blank=True, max_length=254, null=True, verbose_name='Descripción')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('notas_personales', models.TextField(blank=True)),
                ('notas_compartidas', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('nutriologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutriologo.nutriologo')),
            ],
        ),
    ]
