# Generated by Django 3.2.23 on 2023-12-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
    ]
