# Generated by Django 3.2.23 on 2024-01-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20231229_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='correo_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
