# Generated by Django 3.2.23 on 2024-01-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_paciente_correo_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='notificaciones_cambios',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notificaciones_promociones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notificaciones_servicios',
            field=models.BooleanField(default=True),
        ),
    ]
