# Generated by Django 3.2.23 on 2024-01-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20240109_2203'),
        ('paciente', '0004_paciente_contactos'),
    ]

    operations = [
    ]
