# Generated by Django 3.2.23 on 2024-01-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_paciente_solicitudes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='notas_personales',
        ),
    ]
