# Generated by Django 3.2.23 on 2023-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultorio',
            old_name='horario_atencion',
            new_name='horario_apertura',
        ),
        migrations.AddField(
            model_name='consultorio',
            name='horario_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
