# Generated by Django 3.2.23 on 2023-12-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologo', '0005_consultorio_costo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriologo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación'),
        ),
    ]
