# Generated by Django 3.2.23 on 2024-01-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologo', '0006_nutriologo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriologo',
            name='correo_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
