# Generated by Django 3.2.23 on 2024-01-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriologo', '0007_nutriologo_correo_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutriologo',
            name='notificaciones_cambios',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nutriologo',
            name='notificaciones_promociones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutriologo',
            name='notificaciones_servicios',
            field=models.BooleanField(default=True),
        ),
    ]
