# Generated by Django 3.2.23 on 2024-01-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_merge_0004_auto_20240109_2203_0004_paciente_contactos'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='solicitudes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
