# Generated by Django 3.2.24 on 2024-02-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_solicitudagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aviso24h',
            field=models.IntegerField(default=0),
        ),
    ]
