# Generated by Django 3.2.25 on 2024-11-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_evento_aviso24h'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nutrilogo',
            new_name='nutriologo',
        ),
    ]
