ESPECIALIDADES_CHOICES = [
    'Psicología Clínica',
    'Psicología Educativa',
    'Psicología del Deporte',
    'Psicología Organizacional',
    'Psicología Forense',
    'Salud Mental',
    'Terapia Familiar',
    'Neuropsicología',
    'Psicología Infantil',
    'Psicoterapia',
    'Psicología Social',
    'Gerontología',
    'Psicología de la Rehabilitación',
    'Psicología Educacional',
    'Psicología Legal',
    'Orientación Vocacional',
    'Terapia Sexual',
    'Terapia de Pareja',
    'Psicología Transpersonal'
]

ESPECIALIDADES_CHOICES_2 = (
    ('clinica', 'Psicología Clínica'),
    ('educativa', 'Psicología Educativa'),
    ('deporte', 'Psicología del Deporte'),
    ('organizacional', 'Psicología Organizacional'),
    ('forense', 'Psicología Forense'),
    ('salud_mental', 'Salud Mental'),
    ('terapia_familiar', 'Terapia Familiar'),
    ('neuropsicologia', 'Neuropsicología'),
    ('psicologia_infantil', 'Psicología Infantil'),
    ('psicoterapia', 'Psicoterapia'),
    ('psicologia_social', 'Psicología Social'),
    ('gerontologia', 'Gerontología'),
    ('psicologia_rehabilitacion', 'Psicología de la Rehabilitación'),
    ('psicologia_educacional', 'Psicología Educacional'),
    ('psicologia_legal', 'Psicología Legal'),
    ('orientacion_vocacional', 'Orientación Vocacional'),
    ('terapia_sexual', 'Terapia Sexual'),
    ('terapia_pareja', 'Terapia de Pareja'),
    ('psicologia_transpersonal', 'Psicología Transpersonal'),
    ('otra_especialidad', 'Otra Especialidad'),
    # Agrega más especialidaes si es necesario
)