ESPECIALIDADES_CHOICES = [
    'Nutrición Clínica',
    'Nutrición Deportiva',
    'Nutrición Infantil',
    'Nutrición Geriátrica',
    'Nutrición Comunitaria',
    'Nutrición Oncológica',
    'Nutrición Renal',
    'Nutrición Vegetariana y Vegana',
    'Nutrición Funcional',
    'Educación Alimentaria',
    'Nutrición Metabólica',
    'Nutrición en Trastornos de la Conducta Alimentaria',
    'Nutrición en Enfermedades Crónicas',
    'Seguridad Alimentaria',
    'Nutrición y Embarazo',
    'Nutrición Pública',
    'Nutriogenómica',
    'Nutrición de Precisión',
    'Nutrición Bariátrica'
]

ESPECIALIDADES_CHOICES_2 = (
    ('clinica', 'Nutrición Clínica'),
    ('deportiva', 'Nutrición Deportiva'),
    ('infantil', 'Nutrición Infantil'),
    ('geriatrica', 'Nutrición Geriátrica'),
    ('comunitaria', 'Nutrición Comunitaria'),
    ('oncologica', 'Nutrición Oncológica'),
    ('renal', 'Nutrición Renal'),
    ('vegetariana_vegana', 'Nutrición Vegetariana y Vegana'),
    ('funcional', 'Nutrición Funcional'),
    ('educacion_alimentaria', 'Educación Alimentaria'),
    ('metabolica', 'Nutrición Metabólica'),
    ('trastornos_conducta', 'Nutrición en Trastornos de la Conducta Alimentaria'),
    ('enfermedades_cronicas', 'Nutrición en Enfermedades Crónicas'),
    ('seguridad_alimentaria', 'Seguridad Alimentaria'),
    ('embarazo', 'Nutrición y Embarazo'),
    ('publica', 'Nutrición Pública'),
    ('nutriogenomica', 'Nutriogenómica'),
    ('precision', 'Nutrición de Precisión'),
    ('bariatrica', 'Nutrición Bariátrica'),
    ('otra_especialidad', 'Otra Especialidad'),
)
